spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: u298bsehub2uhht4tuumjv60u6ao398p.apps.googleusercontent.com
            clientSecret: z2IPmiWN2bkBEJtrRiALghv_
